os: linux
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=api-mysql
      services:
        - mysql
      before_script:
        - mysql -u root -e "DROP DATABASE IF EXISTS app; CREATE DATABASE app DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
        - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
        - mysql -u root -e "GRANT ALL ON app.* TO 'mysqluser'@'localhost';"
    - python: 3.7
      env: TOXENV=api-postgres
      services:
        - postgresql
      before_script:
        - psql -U postgres -c "CREATE DATABASE app;"
        - psql -U postgres -c "CREATE USER pguser WITH PASSWORD 'pguserpassword';"
services:
  - mongodb
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
